<?php
echo "<!DOCTYPE html>\n"; 
echo "<html lang=\"en\">\n"; 
echo "<head>\n"; 
echo "    <meta charset=\"utf-8\">\n"; 
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"; 
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"; 
echo "    <meta name=\"description\" content=\"\">\n"; 
echo "    <meta name=\"author\" content=\"\">\n"; 
echo "    <title>Venkat Reddy's Portfolio</title>\n"; 
echo "    <!-- Bootstrap Core CSS -->\n"; 
echo "    <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n"; 
echo "    <!-- Custom Fonts -->\n"; 
echo "    <link href=\"vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "    <link href=\"https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\">\n"; 
echo "    <!-- Theme CSS -->\n"; 
echo "    <link href=\"css/grayscale.min.css\" rel=\"stylesheet\">\n"; 
echo "\n"; 
echo "    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n"; 
echo "    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n"; 
echo "    <!--[if lt IE 9]>\n"; 
echo "        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n"; 
echo "        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n"; 
echo "    <![endif]-->\n"; 
echo "</head>\n"; 
echo "\n"; 
echo "<body id=\"page-top\" data-spy=\"scroll\" data-target=\".navbar-fixed-top\">\n"; 
echo "    <!-- Navigation -->\n"; 
echo "    <nav class=\"navbar navbar-custom navbar-fixed-top\" role=\"navigation\">\n"; 
echo "        <div class=\"container\">\n"; 
echo "            <div class=\"navbar-header\">\n"; 
echo "                \n"; 
echo "                <a class=\"navbar-brand page-scroll\">\n"; 
echo "                    <i class=\"fa fa-play-circle\"></i> <span class=\"light\">Venkat</span> Reddy\n"; 
echo "                </a>\n"; 
echo "            </div>\n"; 
echo "            <!-- Collect the nav links, forms, and other content for toggling -->\n"; 
echo "\n"; 
echo "            <!-- /.navbar-collapse -->\n"; 
echo "        </div>\n"; 
echo "        <!-- /.container -->\n"; 
echo "    </nav>\n"; 
echo "    <!-- Intro Header -->\n"; 
echo "\n"; 
echo "    <header class=\"intro\">\n"; 
echo "        <div class=\"intro-body\">\n"; 
echo "            <div class=\"container\">\n"; 
echo "                <br><br>\n"; 
echo "                <br>\n"; 
echo "                <img height=\"700\" width=\"550\" src=\"img/VenkatExperienceLettersoftcopy.jpg\" />\n"; 
echo "               \n"; 
echo "                   \n"; 
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "    </header>\n"; 
echo "    \n"; 
echo "    <br>\n"; 
echo "    <br>\n"; 
echo "    <!-- Map Section -->\n"; 
echo "    <!-- Footer -->\n"; 
echo "   \n"; 
echo "\n"; 
echo "    <!-- jQuery -->\n"; 
echo "    <script src=\"vendor/jquery/jquery.js\"></script>\n"; 
echo "\n"; 
echo "    <!-- Bootstrap Core JavaScript -->\n"; 
echo "    <script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\n"; 
echo "\n"; 
echo "    <!-- Plugin JavaScript -->\n"; 
echo "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js\"></script>\n"; 
echo "\n"; 
echo "    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->\n"; 
echo "    \n"; 
echo "\n"; 
echo "    <!-- Theme JavaScript -->\n"; 
echo "    <script src=\"js/grayscale.min.js\"></script>\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "\n"; 
echo "</html>\n"; 
echo "\n";
?>